import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, FlatList, TouchableOpacity, SafeAreaView, Platform, StatusBar, ActivityIndicator, Modal, ScrollView, Alert, Linking, Dimensions } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { db } from '../lib/firebase';
import { collection, query, where, getDocs, orderBy } from 'firebase/firestore';
import { fetchCollectionData } from '../lib/syncEngine';

export default function HistoryScreen({ navigation }) {
  const [filter, setFilter] = useState('harian'); // harian, mingguan, bulanan
  const [transactions, setTransactions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [totalRevenue, setTotalRevenue] = useState(0);

  // Modal Struk
  const [showReceipt, setShowReceipt] = useState(false);
  const [receiptData, setReceiptData] = useState(null);

  useEffect(() => {
    fetchHistory();
  }, [filter]);

  const fetchHistory = async () => {
    setLoading(true);
    try {
      // Menghitung batas waktu berdasarkan filter
      const now = new Date();
      let startDate = new Date();
      
      if (filter === 'harian') {
        startDate.setHours(0,0,0,0);
      } else if (filter === 'mingguan') {
        startDate.setDate(now.getDate() - 7);
      } else if (filter === 'bulanan') {
        startDate.setMonth(now.getMonth() - 1);
      }

      const q = query(collection(db, 'transactions'), where('created_at', '>=', startDate.toISOString()));
      const data = await fetchCollectionData('transactions', q);

      // Sort descending
      data.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));

      // Fetch items for these transactions
      if (data.length > 0) {
        const allItems = await fetchCollectionData('transaction_items');
        
        data.forEach(trx => {
          trx.transaction_items = allItems.filter(item => item.transaction_id === trx.id);
        });
      }
      
      setTransactions(data);
      const sum = data.reduce((acc, curr) => acc + (curr.total_harga || 0), 0);
      setTotalRevenue(sum);

    } catch (err) {
      console.log('Error fetch history:', err.message);
    } finally {
      setLoading(false);
    }
  };

  const openReceipt = (trx) => {
    const items = trx.transaction_items || [];
    setReceiptData({
      invoice: trx.invoice_number || `TRX-${trx.id}`,
      date: new Date(trx.created_at).toLocaleString('id-ID'),
      method: 'TUNAI/QRIS', // Supabase belum catat method spesifik di trx saat ini
      items: items,
      total: trx.total_harga,
      paid: trx.total_harga,
      change: 0
    });
    setShowReceipt(true);
  };

  const handleExportPDF = async () => {
    try {
      const htmlContent = `
        <html>
          <body style="font-family: Arial; padding: 20px;">
            <h1 style="text-align: center; color: #166534;">Laporan Penjualan Queensha App</h1>
            <p><strong>Periode:</strong> ${filter.toUpperCase()}</p>
            <p><strong>Total Transaksi:</strong> ${transactions.length}</p>
            <p><strong>Total Pendapatan:</strong> Rp ${totalRevenue.toLocaleString('id-ID')}</p>
            <hr/>
            <table style="width: 100%; border-collapse: collapse;">
              <tr style="background-color: #F3F4F6;">
                <th style="padding: 8px; border: 1px solid #E5E7EB;">Invoice</th>
                <th style="padding: 8px; border: 1px solid #E5E7EB;">Tanggal</th>
                <th style="padding: 8px; border: 1px solid #E5E7EB;">Total</th>
              </tr>
              ${transactions.map(t => `
                <tr>
                  <td style="padding: 8px; border: 1px solid #E5E7EB;">${t.invoice_number || t.id}</td>
                  <td style="padding: 8px; border: 1px solid #E5E7EB;">${new Date(t.created_at).toLocaleString('id-ID')}</td>
                  <td style="padding: 8px; border: 1px solid #E5E7EB;">Rp ${t.total_harga.toLocaleString('id-ID')}</td>
                </tr>
              `).join('')}
            </table>
            <p style="text-align: center; font-size: 10px; color: gray; margin-top: 40px;">Generated by Queensha App</p>
          </body>
        </html>
      `;
      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      await Sharing.shareAsync(uri);
    } catch (err) {
      Alert.alert('Error', 'Gagal mengekspor PDF');
    }
  };

  const handleShareWhatsApp = () => {
    const text = `*Laporan Penjualan Queensha App*\n\nPeriode: ${filter}\nTotal Transaksi: ${transactions.length}\nTotal Pendapatan: Rp ${totalRevenue.toLocaleString('id-ID')}\n\nDikirim otomatis dari Queensha App.`;
    const url = `whatsapp://send?text=${encodeURIComponent(text)}`;
    Linking.openURL(url).catch(() => {
      Alert.alert('Gagal', 'Aplikasi WhatsApp tidak terdeteksi.');
    });
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={{padding: 4}}>
          <Ionicons name="arrow-back" size={24} color="#FFF" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Riwayat Penjualan</Text>
        <View style={{flexDirection: 'row'}}>
          <TouchableOpacity onPress={handleExportPDF} style={{padding: 4, marginRight: 8}}>
            <Ionicons name="document-text" size={24} color="#FFF" />
          </TouchableOpacity>
          <TouchableOpacity onPress={handleShareWhatsApp} style={{padding: 4}}>
            <Ionicons name="logo-whatsapp" size={24} color="#FFF" />
          </TouchableOpacity>
        </View>
      </View>

      <View style={styles.filterContainer}>
        {['harian', 'mingguan', 'bulanan'].map(f => (
          <TouchableOpacity 
            key={f} 
            style={[styles.filterBtn, filter === f && styles.filterBtnActive]}
            onPress={() => setFilter(f)}
          >
            <Text style={[styles.filterText, filter === f && styles.filterTextActive]}>
              {f.charAt(0).toUpperCase() + f.slice(1)}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      <View style={styles.summaryCard}>
        <Text style={styles.summaryLabel}>Total Pendapatan ({filter})</Text>
        <Text style={styles.summaryTotal}>Rp {totalRevenue.toLocaleString('id-ID')}</Text>
      </View>

      <View style={styles.content}>
        {loading ? (
          <ActivityIndicator size="large" color="#F97316" style={{marginTop: 40}} />
        ) : (
          <FlatList
            data={transactions}
            keyExtractor={item => item.id.toString()}
            contentContainerStyle={{ paddingBottom: 40 }}
            renderItem={({item}) => {
              const date = new Date(item.created_at).toLocaleString('id-ID', { day:'2-digit', month:'short', hour:'2-digit', minute:'2-digit' });
              return (
                <TouchableOpacity style={styles.trxCard} onPress={() => openReceipt(item)}>
                  <View style={styles.trxIconBg}>
                    <Ionicons name="receipt-outline" size={24} color="#F97316" />
                  </View>
                  <View style={styles.trxInfo}>
                    <Text style={styles.trxInvoice}>{item.invoice_number || `TRX-${item.id}`}</Text>
                    <Text style={styles.trxDate}>{date}</Text>
                  </View>
                  <View style={styles.trxTotal}>
                    <Text style={styles.trxAmount}>Rp {item.total_harga.toLocaleString('id-ID')}</Text>
                    <Ionicons name="chevron-forward" size={16} color="#9CA3AF" />
                  </View>
                </TouchableOpacity>
              );
            }}
            ListEmptyComponent={<Text style={styles.emptyText}>Belum ada transaksi pada periode ini.</Text>}
          />
        )}
      </View>

      {/* MODAL STRUK */}
      <Modal visible={showReceipt} transparent={true} animationType="slide">
        <View style={styles.modalOverlay}>
          <View style={styles.receiptContent}>
            <Text style={styles.receiptStoreName}>Toko Queensha</Text>
            <Text style={styles.receiptAddress}>Jl. Contoh Alamat No. 123</Text>
            <Text style={styles.receiptDivider}>--------------------------------</Text>
            
            {receiptData && (
              <>
                <View style={styles.receiptHeaderRow}>
                  <Text style={styles.receiptText}>{receiptData.date}</Text>
                  <Text style={styles.receiptText}>{receiptData.invoice}</Text>
                </View>
                <Text style={styles.receiptDivider}>--------------------------------</Text>
                
                <ScrollView style={{maxHeight: 250, marginVertical: 8}}>
                  {receiptData.items.map((item, idx) => (
                    <View key={idx} style={{marginBottom: 4}}>
                      <Text style={styles.receiptItemName}>{item.product_name}</Text>
                      <View style={styles.receiptItemRow}>
                        <Text style={styles.receiptText}>{item.jumlah} x Rp {item.harga_satuan.toLocaleString('id-ID')}</Text>
                        <Text style={styles.receiptText}>Rp {(item.jumlah * item.harga_satuan).toLocaleString('id-ID')}</Text>
                      </View>
                    </View>
                  ))}
                </ScrollView>
                
                <Text style={styles.receiptDivider}>--------------------------------</Text>
                <View style={styles.receiptTotalRow}>
                  <Text style={styles.receiptTotalText}>Total</Text>
                  <Text style={styles.receiptTotalText}>Rp {receiptData.total.toLocaleString('id-ID')}</Text>
                </View>
              </>
            )}

            <Text style={styles.receiptFooter}>Terima Kasih Atas Kunjungan Anda</Text>

            <View style={[styles.modalActions, { marginTop: 24 }]}>
              <TouchableOpacity style={styles.modalCancelBtn} onPress={() => setShowReceipt(false)}>
                <Text style={styles.modalCancelText}>Tutup</Text>
              </TouchableOpacity>
              <TouchableOpacity style={[styles.modalConfirmBtn, { backgroundColor: '#2563EB', flexDirection: 'row', justifyContent: 'center' }]} onPress={() => Alert.alert('Mencetak', 'Menghubungkan ke printer bluetooth...')}>
                <Ionicons name="print" size={20} color="#FFF" style={{marginRight: 8}} />
                <Text style={styles.modalConfirmText}>Print</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </Modal>

    </SafeAreaView>
  );
}

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');
const isTablet = Math.min(screenWidth, screenHeight) >= 600;

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F9FAFB', paddingTop: (Platform.OS === 'android' && !isTablet) ? StatusBar.currentHeight : 0 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, height: 60, backgroundColor: '#F97316' },
  headerTitle: { fontSize: 18, fontWeight: 'bold', color: '#FFF' },
  
  filterContainer: { flexDirection: 'row', backgroundColor: '#FFF', padding: 12, borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  filterBtn: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 8 },
  filterBtnActive: { backgroundColor: '#FFEDD5' },
  filterText: { fontSize: 14, fontWeight: '600', color: '#6B7280' },
  filterTextActive: { color: '#D97706' },

  summaryCard: { backgroundColor: '#166534', margin: 16, padding: 20, borderRadius: 16, alignItems: 'center', elevation: 4, shadowColor: '#000', shadowOpacity: 0.1, shadowOffset: {width: 0, height: 2} },
  summaryLabel: { color: '#DCFCE7', fontSize: 14, marginBottom: 8 },
  summaryTotal: { color: '#FFF', fontSize: 28, fontWeight: 'bold' },

  content: { flex: 1, paddingHorizontal: 16 },
  trxCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', padding: 16, borderRadius: 12, marginBottom: 12, borderWidth: 1, borderColor: '#E5E7EB' },
  trxIconBg: { width: 48, height: 48, borderRadius: 12, backgroundColor: '#FFEDD5', justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  trxInfo: { flex: 1 },
  trxInvoice: { fontSize: 14, fontWeight: 'bold', color: '#111827', marginBottom: 4 },
  trxDate: { fontSize: 12, color: '#6B7280' },
  trxTotal: { alignItems: 'flex-end', flexDirection: 'row', gap: 8 },
  trxAmount: { fontSize: 14, fontWeight: 'bold', color: '#166534' },
  emptyText: { textAlign: 'center', color: '#9CA3AF', marginTop: 40 },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  receiptContent: { backgroundColor: '#FFF', borderRadius: 8, padding: 24, width: 320, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 10, elevation: 5 },
  receiptStoreName: { fontSize: 20, fontWeight: 'bold', textAlign: 'center', color: '#111827', marginBottom: 4 },
  receiptAddress: { fontSize: 12, textAlign: 'center', color: '#6B7280', marginBottom: 12 },
  receiptDivider: { fontSize: 14, textAlign: 'center', color: '#9CA3AF', marginVertical: 8, letterSpacing: 2 },
  receiptHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  receiptText: { fontSize: 12, color: '#374151', fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  receiptItemName: { fontSize: 12, color: '#111827', fontWeight: 'bold', fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  receiptItemRow: { flexDirection: 'row', justifyContent: 'space-between' },
  receiptTotalRow: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 8 },
  receiptTotalText: { fontSize: 14, fontWeight: 'bold', color: '#111827', fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  receiptFooter: { fontSize: 12, textAlign: 'center', color: '#6B7280', marginTop: 16, fontStyle: 'italic' },
  
  modalActions: { flexDirection: 'row', gap: 12 },
  modalCancelBtn: { flex: 1, paddingVertical: 14, borderRadius: 8, backgroundColor: '#E5E7EB', alignItems: 'center' },
  modalCancelText: { color: '#4B5563', fontWeight: 'bold', fontSize: 16 },
  modalConfirmBtn: { flex: 1, paddingVertical: 14, borderRadius: 8, backgroundColor: '#166534', alignItems: 'center' },
  modalConfirmText: { color: '#FFF', fontWeight: 'bold', fontSize: 16 },
});
